// EXE201/app/src/main/java/com/android/birdlens/data/model/AIModels.kt
package com.android.birdlens.data.model

import com.google.gson.annotations.SerializedName

// Logic: This data class represents the expected JSON response from the new
// backend endpoint (/ai/identify-bird). It mirrors the results previously
// generated by the on-device Gemini model, allowing the ViewModel to process
// the backend's response in a similar way.
data class AIIdentifyResponse(
    @SerializedName("possibilities") val possibilities: List<String>?,
    @SerializedName("identified_bird") val identifiedBird: String?,
    @SerializedName("chat_response") val chatResponse: String?,
    @SerializedName("image_url") val imageUrl: String?
)

// Logic: This model represents a message in the conversation history. It will be
// sent to the backend for context in follow-up questions.
data class ChatMessage(
    @SerializedName("role") val role: String, // "user" or "model"
    @SerializedName("text") val text: String
)

// Logic: This model represents the request body for asking a follow-up question.
data class AIQuestionRequest(
    @SerializedName("bird_name") val birdName: String,
    @SerializedName("question") val question: String,
    @SerializedName("history") val history: List<ChatMessage>
)

// Logic: This model represents the response from the follow-up question endpoint.
data class AIQuestionResponse(
    @SerializedName("chat_response") val chatResponse: String
)